### ISSUE TITLE
Change port

### ISSUE THREAD

**Issue by anbzerc** [Scrybbling-together/scrybble-site#5]
It seems that the 80 port can only be opened by root user, so if you want the script to work rootless, you must change the port :/

`rror response from daemon: driver failed programming external connectivity on endpoint scrybble-site-laravel.test-1 (063cfcdeae98c2bf2770dbab8df93ae57b10283a83013a3d46893feb14ad70b3): Error starting userland proxy: error while calling PortManager.AddPort(): cannot expose privileged port 80, you can add 'net.ipv4.ip_unprivileged_port_start=80' to /etc/sysctl.conf (currently 1024), or set CAP_NET_BIND_SERVICE on rootlesskit binary, or choose a larger port number (>= 1024): listen tcp4 0.0.0.0:80: bind: permission denied`
 plus https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux

**Comment by Azeirah** [comment]
I don't think port 80 is disabled for a regular user on Ubuntu by default, right?

The port can also be changed in the env file, this is just dockerized Laravel after all.

**Comment by Azeirah** [comment]
> Problem was because docker was run rootless. According to https://serverfault.com/questions/112795/how-to-run-a-server-on-port-80-as-a-normal-user-on-linux , port below 1024 can only be opened by the root

Hmm, I've never had that issue myself. Though if I run `python -m http.server 80` I do get a permission denied error, so I suppose it's right.

I can change the default port to something else in that case, most of the time I see people use 8000 or 8080, since those are also pretty standard web ports.

**Comment by Azeirah** [comment]
> Otherwise docker's official solution seems to work

What do you mean by their official solution? The stackoverflow solution you posted is using an Ubuntu fix.

I'd rather respect ubuntu defaults than messing with config.

**Comment by Azeirah** [comment]
> I mean this https://docs.docker.com/engine/security/rootless/#exposing-privileged-ports , which follows the docker rootless config docs I've done

Oh apologies, I was thinking of the serverfault link.

I'm just gonna change the default port to 8000, it's less configuration and is still quite standard.
